name: Build and Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libssl-dev libbsd-dev python3-dev build-essential devscripts debhelper

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pytest

    - name: Test wheel build
      run: |
        python -m build --wheel

    - name: Test Debian package build
      run: |
        debuild -ui -uc -b

    - name: Install and test packages
      run: |
        sudo dpkg -i ../libtruenas-pwenc1_*.deb
        sudo dpkg -i ../libtruenas-pwenc-dev_*.deb
        sudo dpkg -i ../python3-truenas-pwenc_*.deb
        python -m pytest tests/ -v